sudo: required
services:
  - docker

before_install:
  - docker build -t ryokinoshita/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ryokinoshita/react-test npm test

after_success:
  - docker build -t ryokinoshita/multi-client ./client
  - docker build -t ryokinoshita/multi-nginx ./nginx
  - docker build -t ryokinoshita/multi-server ./server
  - docker build -t ryokinoshita/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those iamges and push them to docker hub
  - docker push ryokinoshita/multi-client
  - docker push ryokinoshita/multi-nginx
  - docker push ryokinoshita/multi-server
  - docker push ryokinoshita/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'ap-northeast-1'
  app: 'multi-docker'
  env: 'Multidocker-env'
  bucket_name: 'elasticbeanstalk-ap-northeast-1-165742325952'
  bucket_path: 'docker-multi'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
