sudo: required
services:
  - docker 

before_install: 
  - docker build -t ryokinoshita/react-test -f ./client/Dockerfile.dev ./client
  - docker build myotherproject
  
script:
  - docker run -e CI=true ryokinoshita/react-test npm test

after_success: 
  - docker build -t ryokinoshita/multi-client ./client
  - docker build -t ryokinoshita/multi-client ./nginx
  - docker build -t ryokinoshita/multi-client ./server
  - docker build -t ryokinoshita/multi-client ./worker
